#!/bin/sh

echo "Running init_sh, mounting some stuff and starting erlinit"
mount -t devtmpfs -o rw none /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys
exec /sbin/init
#mkdir /media/root
#echo "Mounting /dev/mmcblk0p2..."
#mount /dev/mmcblk0p2 /media/root
#echo "Mounted /media/root"

#mount /dev/mapper/appfs /media/mmcblk0p2
# else
#     mkdir /media/mmcblk0p2
#     mount /dev/mmcblk0p2 /media/mmcblk0p2
#     mkdir /root/mmcblk0p2
#     cp -r /media/mmcblk0p2/* /root/mmcblk0p2/
#     umount /media/mmcblk0p2
#     cryptsetup -q luksFormat --type=luks2 --key-file="$KEY_PATH" --pbkdf argon2id /dev/mmcblk0p2
#     cryptsetup open --type=luks2 --key-file "$KEY_PATH" /dev/mmcblk0p2 appfs
#     /usr/sbin/mke2fs -t ext4 /dev/mapper/appfs
#     mount /dev/mapper/appfs /media/mmcblk0p2
#     cp -r /root/mmcblk0p2/* /media/mmcblk0p2/
# fi

#echo "Not switching root."
#echo "Switching root :)"
#exec switch_root /media/root/ /sbin/init